postgres: &postgres
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5

development:
  <<: *postgres
  database: gamebus_development

test:
  <<: *postgres
  database: gamebus_test

production:
  <<: *postgres
  database: gamebus_production
  pool: 20
