# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4825a39d9785185c18cb67850e10aeb16f4155452175f02e17dd37b13dcb4dce2c7c73c55e88d83ff624428e4568de6b04352a6daeb90caebc6bd4d499984ea5
  gamebus_app_key: 9VVQLphWOSqP59AW # Old invalid key
  rvs_url: 'https://staging-rowing.tracklete.io/'
  gamebus_url: 'https://gamebus.synersec.eu'

test:
  secret_key_base: 10b093529e718fb27fe27e98d68595a0f87adcd998e52856bb669a43d7a4f6ed62714985aecc0439332edae756bc92d6fa2b2fd1d621edd712b64ec6af9e1448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gamebus_app_key: <%= ENV["GAMEBUS_APP_KEY"] %>
  rvs_url: 'https://rowing.tracklete.io/'
  gamebus_url: 'https://gamebus.synersec.eu'
